### PR TITLE
API Move (part 2)

### PR DESCRIPTION
**Pull request by robertsanseries**
Below is the implementation responsible for getting the values of the class MyJsonReader

Note: _I'm already integrating this part into the application_

```vala
MyJsonReader jsonReader = new MyJsonReader (text);
                
GLib.warning ("audioFile: " + jsonReader.audioFile);
GLib.warning ("word: " + jsonReader.word);

foreach (Gee.HashMap json_entries in jsonReader.entries) {

    foreach (var entry in json_entries.entries) {

        if("grammaticalFeatures" == (string) entry.key) {

            Gee.ArrayList<Gee.HashMap> grammaticalFeatures_list  = (Gee.ArrayList<Gee.HashMap>) entry.value;

            foreach (Gee.HashMap grammaticalFeatures_item  in grammaticalFeatures_list) {
                foreach (var grammaticalFeatures_entrie in grammaticalFeatures_item.entries) {
                    warning ("%s => %s\n", (string) grammaticalFeatures_entrie.key, (string) grammaticalFeatures_entrie.value);
                }
            }
        }

        if("senses" == (string) entry.key) {
            
            Gee.ArrayList<Gee.HashMap> senses_list  = (Gee.ArrayList<Gee.HashMap>) entry.value;

            foreach (Gee.HashMap senses_item  in senses_list) {
                foreach (var senses_entrie in senses_item.entries) {
                    
                    if("definitions" == (string) senses_entrie.key) {
                        var definitions = (Gee.ArrayList<string>) senses_entrie.value;
                        warning ("definitions: " + definitions.get(0));
                    }

                    if("examples" == (string) senses_entrie.key) {
                        var examples_list = (Gee.ArrayList<Gee.ArrayList>) senses_entrie.value;

                        foreach (Gee.ArrayList<string> examples_item in examples_list) {
                            foreach (string exemple in examples_item) {
                                warning ("examples: " + exemple);
                            }
                        }
                    }
                }
            }
        }
    }
}
```

### CODE REVIEW

**Comment by lainsce** [comment]
I'm going to wait until you implement this with the GUI to merge this PR

**Comment by lainsce** [comment]
This is just a comment to alert you about this PR being stale without modifications for over a week. Please show any signal of this being worked on or I'll need you to mske a new PR.

**Comment by robertsanseries** [comment]
@lainsce Sorry, I'm going to work on it tomorrow! and already I must finish it.

**Comment by lainsce** [comment]
This is not needed anymore, thanks anyway!

**Pull request closed without merging**
